FROM alpine
# base image alpine kullanır
WORKDIR /wordpress-uygulamasi
# dizin değiştirdik
ADD https://tr.wordpress.org/latest-tr_TR.tar.gz .
# url'den dosyayı dizine kopyaladık, buradaki olay uzak bir sunucudaki dosyayı buraya kopyalayabilmekti
# fakat decompress olarak atmasını istersek aynı dizindeki dosyayı (.tar) vermemiz gerekir